- name: Start WebLogic Managed Servers (Cluster)
  hosts: weblogic
  become: yes
  tasks:
    - name: Start Managed Server 1
      shell: nohup /home/weblogic/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/bin/startManagedWebLogic.sh ICICI http://192.168.73.128:7001 > /home/weblogic/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/bin/ms1.out 2>&1 &

    - name: Start Managed Server 2
      shell: nohup /home/weblogic/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/bin/startManagedWebLogic.sh SBI http://192.168.73.128:7001 > /home/weblogic/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/bin/ms2.out 2>&1 &