- name: Start WebLogic Node Manager
  hosts: weblogic
  become: yes
  tasks:
    - name: Start Node Manager
      shell: nohup /home/weblogic/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/bin/startNodeManager.sh > /home/weblogic/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/bin/nodemanager.out 2>&1 &
      args:
        chdir: /home/weblogic/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/bin