- name: Start WebLogic Admin Server
  hosts: weblogic
  become: yes
  tasks:
    - name: Start Admin Server
      shell: nohup /home/weblogic/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/bin/startWebLogic.sh > /home/weblogic/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/bin/adminserver.out 2>&1 &
      args:
        chdir: /home/weblogic/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain