- name: Stop WebLogic Managed Servers (Cluster)
  hosts: weblogic
  become: yes
  tasks:
    - name: Stop Managed Server 1
      shell: pkill -f 'weblogic.Name=ICICI'

    - name: Stop Managed Server 2
      shell: pkill -f 'weblogic.Name=SBI'